---
title: "finalproject"
author: "Kiera O'Brien"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(ggplot2)
library(dplyr)
library(vctrs)
library(rsconnect)
library(shiny)
library(haven)
library(readxl)
library(gganimate)
library(shinydashboard)
library(shinyWidgets)

rsconnect::setAccountInfo(name='kieraobrien',
			  token='D36A6A60ACFFD2CA1CB5F3ED10FE5C4C',
			  secret='Hx28vDzuEizm14tABGzGmdr/B7WFerO7MLHYzILd')
```

``` {r data, include = F}

# Note: each of these datasets comes with a guide for interpretation.
# It is on the CCES website. I used it to help select useful questions.
# https://cces.gov.harvard.edu/, under each year. 

# reading in excel file of CCES 2018 data

cces2018 <- read_excel("cces2018.xlsx")

cces2018 <- na.omit(cces2018)
View(cces2018)
```

```{r Republicans}

rsonly <- cces2018 %>%
  mutate(category = case_when(
    (cces2018$pid7) == 5 ~ "Lean Republican",
    (cces2018$pid7) == 6 ~ "Not Very Strong Republican",
    (cces2018$pid7) == 7 ~ "Strong Republican",
    ))

rsonly <- na.omit(rsonly)

yrsonly <- rsonly %>%
  mutate(age = (2020 - rsonly$birthyr))


```

``` {r plot, echo = F, warning = F}

# creating ggplot for EPA CO2 regulation

figure1 <- ggplot(rsonly, 
                  aes(x = rsonly$CO2)) + 
  geom_bar(mapping = NULL, stat = "count", fill = "lightsteelblue", 
           color = "lightsteelblue") + 
  labs(title = "Should the EPA Regulate CO2?", 
       x = "Support                  Oppose", 
       y = "Count", 
       caption = "Based on data from the Cooperative Congressional Election Study, 2018") + 
  scale_x_discrete(labels=c("1" = "Support", "2" = "Oppose")) + 
  theme(plot.title = element_text(face = "bold", 
                                  size = 17))
figure1
```

```{r compare, echo = F}

action <- cces2018 %>%
  select(CO2, MPG, Reneww, JobsVEnvir, Paris) %>%
  mutate(category = case_when(
    (cces2018$CO2) == 1 ~ "EPA Regulation of CO2",
    (cces2018$MPG) == 1 ~ "MPG Standards",
    (cces2018$Reneww) == 1 ~ "Renewable Portfolios",
    (cces2018$JobsVEnvir) == 1 ~ "Environment > Jobs",
    (cces2018$Paris) == 1 ~ "Paris Agreement"))

# plotting density and filling by cased categories
# assigning themes and correcting labels

figure2 <- cces2018 %>%  
  ggplot(aes(action$category, fill = action$category)) +
  geom_density(alpha = .4, colour = "black", size = 0.73) +
  labs(fill = "Climate Action Supported", title = "Support for Federal Climate Actions", x = "Climate Action Supported", y = "Support Relative to Other Actions", caption = "Data from the Cooperative Congressional Election Study (2018)") + 
  scale_x_discrete(labels = NULL) +
  scale_fill_brewer(palette = 3, direction = -1, na.value = "grey50") + 
  transition_manual(action$category) +
  theme_classic() + 
  theme(plot.title = element_text(face = "bold", 
                                  size = 17))
figure2
```

``` {r shiny, include = F}

ui <- fluidPage(
  plotOutput(outputId = "figure2")
)
server <- function(input, output) {
  output$figure2 <- renderPlot({figure2
    
  })
}
shinyApp(ui = ui, server = server)
```
